# Data import and storage
Input and output typically falls into a few main categories: reading text files and other more efficient on-disk formats like pdf and docx files, interacting with net-work sources like web APIs, and loading data from databases.

## Reading and writing a text file
### Using `open()` to read and write

`open()` returns a file object, and is most commonly used with two arguments: `open(filename, mode)`. It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes.

- `mode` can be 'r' for read
- 'w' for only writing
- 'a' opens the file for appending
- 'r+' opens the file for both reading and writing


In [37]:
with open("data/BABAnews.txt", mode = 'r') as myfile: 
        print(myfile.read())

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



In [38]:
myfile.closed

True

If you’re not using the with keyword, then you should call f.close() to close the file and immediately free up any system resources used by it. For example:

In [72]:
myfile = open("data/BABAnews.txt", mode = 'r')
text = myfile.read()
myfile.close()
print(text)

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



972

In [42]:
myfile.read() # can be read after the file being closed

ValueError: I/O operation on closed file.

To read the contents of a file, we use `f.read(size)`. 

In [48]:
myfile = open("data/BABAnews.txt", mode = 'r')
myfile.read()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n'

In [49]:
myfile.read()
myfile.close()

''

`f.readline()` reads a single line from the file; a newline character (\n) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline. This makes the return value unambiguous; if `f.readline()` returns an empty string, the end of the file has been reached, while a blank line is represented by '\n', a string containing only a single newline. 

If you want to read all the lines of a file in a list you can also use `list(f)` or `f.readlines()`.

In [77]:
myfile = open("data/BABAnews.txt", mode = 'r')
myfile.readline()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n'

In [78]:
myfile.readlines()

['    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n',
 '    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n',
 '    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n',
 '    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n']

**Note:** Both `read()` and `readlines()` come with the concept of a cursor. After either command is executed, the cursor moves to the end of the file, leaving nothing more to read in. Therefore, once a file content has been read in, another attempt to read from the file object will produce an empty data object. If for some reason you must read the file content again, you must close and re-open the file. 

Lastly, rather than loading the entire file content into memory, you can iterate through the file object line by line using the `for` loop. This method is more memory-efficient and therefore recommended when dealing with a very large file. 

In [76]:
with open('data/Titanic.csv', 'r') as myfile:
    for line in myfile:
        print(line, end ='')

ID,Class,Sex,Age,Survived,Freq
1,1st,Male,Child,No,0
2,2nd,Male,Child,No,0
3,3rd,Male,Child,No,35
4,Crew,Male,Child,No,0
5,1st,Female,Child,No,0
6,2nd,Female,Child,No,0
7,3rd,Female,Child,No,17
8,Crew,Female,Child,No,0
9,1st,Male,Adult,No,118
10,2nd,Male,Adult,No,154
11,3rd,Male,Adult,No,387
12,Crew,Male,Adult,No,670
13,1st,Female,Adult,No,4
14,2nd,Female,Adult,No,13
15,3rd,Female,Adult,No,89
16,Crew,Female,Adult,No,3
17,1st,Male,Child,Yes,5
18,2nd,Male,Child,Yes,11
19,3rd,Male,Child,Yes,13
20,Crew,Male,Child,Yes,0
21,1st,Female,Child,Yes,1
22,2nd,Female,Child,Yes,13
23,3rd,Female,Child,Yes,14
24,Crew,Female,Child,Yes,0
25,1st,Male,Adult,Yes,57
26,2nd,Male,Adult,Yes,14
27,3rd,Male,Adult,Yes,75
28,Crew,Male,Adult,Yes,192
29,1st,Female,Adult,Yes,140
30,2nd,Female,Adult,Yes,80
31,3rd,Female,Adult,Yes,76
32,Crew,Female,Adult,Yes,20

Writing methods also come in a pair: `write()` and `writelines()`. Like the corresponding reading methods, `write()` handles a single string, while `writelines()` handles a list of strings. 

Below, `write()` writes a single string each time to the designated output file:

In [66]:
file = open('data/testfile.txt', 'w') 
file.write('Hello World \n') 
file.write('and this is another line.') 
file.close() 

In [ ]:
This time, we have `tobuy`, a list of strings, which `writelines()` writes out at once:

In [79]:
tobuy = ['milk\n', 'butter\n', 'coffee beans\n', 'arugula\n']
file = open('data/grocerylist.txt', 'w')
file.writelines(tobuy) # writelines(list)
file.close()

**Only the string type can be written.** Writing methods only works with strings: `write()` takes a single string, and `writelines()` takes a list which contains strings only. Non-string type data must be first coerced into the string type by using the `str()` function. 

In [80]:
pi = 3.141592
fout = open('data/math.txt', 'w')
fout.write("Pi's value is ")
fout.write(pi) # trying to write float, doesn't work

TypeError: write() argument must be str, not float

In [81]:
fout.write(str(pi))
fout.close()

### Other ways to read text files

We can also use other modules to read text files. For example, we can use **numpy** to read *txt* file.  **csv** and **pandas** can be used to read *csv* files.

In [88]:
import numpy as np 
data = np.loadtxt('data/BJsales.txt', skiprows = 1, delimiter='\t')
print(data)

[[  1.    1.  200.1]
 [  2.    2.  199.5]
 [  3.    3.  199.4]
 [  4.    4.  198.9]
 [  5.    5.  199. ]
 [  6.    6.  200.2]
 [  7.    7.  198.6]
 [  8.    8.  200. ]
 [  9.    9.  200.3]
 [ 10.   10.  201.2]
 [ 11.   11.  201.6]
 [ 12.   12.  201.5]
 [ 13.   13.  201.5]
 [ 14.   14.  203.5]
 [ 15.   15.  204.9]
 [ 16.   16.  207.1]
 [ 17.   17.  210.5]
 [ 18.   18.  210.5]
 [ 19.   19.  209.8]
 [ 20.   20.  208.8]
 [ 21.   21.  209.5]
 [ 22.   22.  213.2]
 [ 23.   23.  213.7]
 [ 24.   24.  215.1]
 [ 25.   25.  218.7]
 [ 26.   26.  219.8]
 [ 27.   27.  220.5]
 [ 28.   28.  223.8]
 [ 29.   29.  222.8]
 [ 30.   30.  223.8]
 [ 31.   31.  221.7]
 [ 32.   32.  222.3]
 [ 33.   33.  220.8]
 [ 34.   34.  219.4]
 [ 35.   35.  220.1]
 [ 36.   36.  220.6]
 [ 37.   37.  218.9]
 [ 38.   38.  217.8]
 [ 39.   39.  217.7]
 [ 40.   40.  215. ]]


In [60]:
import csv
with open('data/Titanic.csv') as csvfile:
    titanicReader = csv.reader(csvfile)
    for row in titanicReader:
        print('  '.join(row))

ID  Class  Sex  Age  Survived  Freq
1  1st  Male  Child  No  0
2  2nd  Male  Child  No  0
3  3rd  Male  Child  No  35
4  Crew  Male  Child  No  0
5  1st  Female  Child  No  0
6  2nd  Female  Child  No  0
7  3rd  Female  Child  No  17
8  Crew  Female  Child  No  0
9  1st  Male  Adult  No  118
10  2nd  Male  Adult  No  154
11  3rd  Male  Adult  No  387
12  Crew  Male  Adult  No  670
13  1st  Female  Adult  No  4
14  2nd  Female  Adult  No  13
15  3rd  Female  Adult  No  89
16  Crew  Female  Adult  No  3
17  1st  Male  Child  Yes  5
18  2nd  Male  Child  Yes  11
19  3rd  Male  Child  Yes  13
20  Crew  Male  Child  Yes  0
21  1st  Female  Child  Yes  1
22  2nd  Female  Child  Yes  13
23  3rd  Female  Child  Yes  14
24  Crew  Female  Child  Yes  0
25  1st  Male  Adult  Yes  57
26  2nd  Male  Adult  Yes  14
27  3rd  Male  Adult  Yes  75
28  Crew  Male  Adult  Yes  192
29  1st  Female  Adult  Yes  140
30  2nd  Female  Adult  Yes  80
31  3rd  Female  Adult  Yes  76
32  Crew  Female  Adult  Yes

The `pandas` I/O API is a set of top level `reader` functions accessed like `read_csv()` that generally return a pandas object. These functions includes

    read_excel
    read_hdf
    read_sql
    read_json
    read_msgpack (experimental)
    read_html
    read_gbq (experimental)
    read_stata
    read_sas
    read_clipboard
    read_pickle
    
See [pandas IO tools](http://pandas.pydata.org/pandas-docs/stable/io.html) for detailed explanation.

In [61]:
import pandas as pd
titanicData = pd.read_csv('data/Titanic.csv') 
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

We could also have used `read_table()` and specifying the delimiter:

In [84]:
titanicData = pd.read_table('data/Titanic.csv', sep=',')
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

A file will not always have a header row. To read this in, you have a couple of options. You can allow pandas to assign default column names, or you can specify names yourself:

In [92]:
sales = pd.read_csv('data/BJsales.csv', header = None)
sales.head()

0  1      2
0  1  1  200.1
1  2  2  199.5
2  3  3  199.4
3  4  4  198.9
4  5  5  199.0

In [94]:
sales = pd.read_csv('data/BJsales.csv', names=['ID', 'Time', 'Value'])
sales.head()

ID  Time  Value
0   1     1  200.1
1   2     2  199.5
2   3     3  199.4
3   4     4  198.9
4   5     5  199.0

Data can also be exported to delimited format. Let’s consider one of the CSV files read above:

In [97]:
sales.to_csv('data/sales.csv', index = False)

## Reading a Microsoft Excel file using `pandas`

Excel files are a huge part of any business operation and it becomes imperative that you learn exactly how to import these into python for data analysis. In order to do this we can use the code snippet shown below:

In [102]:
import pandas as pd
file = 'data/example.xlsx'
myfile = pd.ExcelFile(file) 
print(myfile.sheet_names) #printing out all the sheet names in the excel file
dataframe = myfile.parse('HairEyeColor') #extracting data from the first sheet as a dataframe
dataframe.head()

['HairEyeColor', 'Nile']


ID   Hair    Eye   Sex  Freq
0   1  Black  Brown  Male    32
1   2  Brown  Brown  Male    53
2   3    Red  Brown  Male    10
3   4  Blond  Brown  Male     3
4   5  Black   Blue  Male    11

## Reading a pdf file using `PyPDF2`

`PyPDF2` is a python library built as a PDF toolkit. It is capable of:

- Extracting document information (title, author, …)
- Splitting documents page by page
- Merging documents page by page
- Cropping pages
- Merging multiple pages into a single page
- Encrypting and decrypting PDF files
- and more!

Here we only demonstrate how to read a pdf file. Please find more details on https://pypi.org/project/PyPDF2/.

In [8]:
import PyPDF2
pdfFileObj = open('data/Li2011Wiley.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
pdfReader.numPages
pageObj = pdfReader.getPage(0)
print(pageObj.extractText())
pdfFileObj.close()

MODELINGCONDITIONALDENSITIESUSINGFINITESMOOTH
MIXTURES
FENGLI,MATTIASVILLANI,ANDROBERTKOHN
SverigesRiksbankWorkingPaperSeriesNo.245
August2010
Abstract.
Smoothmixtures,i.e.mixturemodelswithcovariate-depen
dentmixingweights,
areveryusefulexiblemodelsforconditionaldensities.P
reviousworkshowsthatusingtoo
simplemixturecomponentsformodelingheteroscedastican
d/orheavytaileddatacangive
apoort,evenwithalargenumberofcomponents.Thispapere
xploreshowwellasmooth
mixtureofsymmetriccomponentscancaptureskeweddata.Si
mulationsandapplicationson
realdatashowthatincludingcovariate-dependentskewnes
sinthecomponentscanleadto
substantiallyimprovedperformanceonskeweddata,oftenu
singamuchsmallernumberof
components.Furthermore,variableselectioniseectivei
nremovingunnecessarycovariatesin
theskewness,whichmeansthatthereislittlelossinallowi
ngforskewnessinthecomponents
whenthedataareactuallysymmetric.Wealsointroducesmoo
thmixturesofgammaand
log-normalcomponentstomodelpositively-valuedrespons
evariables.
Keywords

## Reading a word file using `docx`

In [127]:
import docx
doc = docx.Document('data/Li2011Wiley.docx')
print(len(doc.paragraphs))
print(doc.paragraphs[0].text)

6
MODELING CONDITIONAL DENSITIES USING FINITE SMOOTH MIXTURES


## Interacting with HTML and Web APIs

Many websites have public APIs providing data feeds via JSON or some other format. There are a number of ways to access these APIs from Python; one easy-to-use method that I recommend is the requests package (http://docs.python-requests.org). 

In [136]:
import requests
url = 'https://sp0.baidu.com/8aQDcjqpAAV3otqbppnN2DJv/api.php?resource_id=6899&query=失信执行人名单&iname=中国银行'
resp = requests.get(url)
import json
data = json.loads(resp.text, encoding='gb18030')
data.keys()

dict_keys(['status', 't', 'set_cache_time', 'data'])

In [137]:
result = data['data'][0]['result']
for i in range(len(result)):
        data = result[i]
        caseCode = data['caseCode']
        areaName = data['areaName']
        businessEntity = data['businessEntity']
        courtName = data['courtName']
        duty = data['duty']
        performance = data['performance']
        disruptTypeName = data['disruptTypeName']
        publishDate = data['publishDate']
        regDate = data['regDate']
        gistId = data['gistId']
        gistUnit = data['gistUnit']
        cardNum = data['cardNum']
        print('  '.join([caseCode, areaName, businessEntity, courtName, duty, performance, disruptTypeName, publishDate, regDate, gistId, gistUnit, cardNum]))


(2010)历执字第00787号  山东  李光  济南市历下区人民法院  一、被告偿还原告15834.4元；二、被告更正原告的个人信用信息并上报于中国人民银行征信管理机构，为原告恢复银行信用记录，如因技术原因，中国人民银行征信管理机构无法更正信息，由被告中国银行股份有限公司济南分行与中国人民银行征信管理机构协商对原告黄金华的个人信用作特殊标记，以区别于其他不良信息，于本调解书生效之日起20日内执行；三、原、被告其余责任互不追究。  全部未履行  其他有履行能力而拒不履行生效法律文书确定义务  2015年08月25日  20100331  （2007）历民初字第3036号  济南市历下区人民法院  863152018
(2015)龙泉执字第01421号  四川  林忠  龙泉驿区人民法院  中国银行股份有限公司成都航天城支行于本判决生效之日起向潘兴才支付存款损失94890元及利息。  全部未履行  违反财产报告制度,其他有履行能力而拒不履行生效法律文书确定义务  2015年08月10日  20150727  （2015）成民终字第2016号民事判决书  四川省成都市中级人民法院  782689497


## Interacting with Databases

In many applications data rarely comes from text files, that being a fairly inefficient way to store large amounts of data. SQL-based relational databases (such as SQL Server, PostgreSQL, and MySQL) are in wide use, and many alternative non-SQL (so-called NoSQL) databases have become quite popular. The choice of database is usually de- pendent on the performance, data integrity, and scalability needs of an application.

Loading data from SQL into a DataFrame is fairly straightforward, and pandas has some functions to simplify the process. As an example, I’ll use an in-memory SQLite database using Python’s built-in sqlite3 driver. Here’s a short Python program that selects latitudes and longitudes from an SQLite database stored in a file called survey.db:

In [ ]:
import sqlite3
connection = sqlite3.connect("survey.db")
cursor = connection.cursor()
cursor.execute("SELECT Site.lat, Site.long FROM Site;")
results = cursor.fetchall()
for r in results:
    print(r)
cursor.close()
connection.close()

The program starts by importing the sqlite3 library. If we were connecting to MySQL, DB2, or some other database, we would import a different library, but all of them provide the same functions, so that the rest of our program does not have to change (at least, not much) if we switch from one database to another.

Line 2 establishes a connection to the database. Since we’re using SQLite, all we need to specify is the name of the database file. Other systems may require us to provide a username and password as well. Line 3 then uses this connection to create a cursor. Just like the cursor in an editor, its role is to keep track of where we are in the database.

On line 4, we use that cursor to ask the database to execute a query for us. The query is written in SQL, and passed to cursor.execute as a string. It’s our job to make sure that SQL is properly formatted; if it isn’t, or if something goes wrong when it is being executed, the database will report an error.

The database returns the results of the query to us in response to the cursor.fetchall call on line 5. This result is a list with one entry for each record in the result set; if we loop over that list (line 6) and print those list entries (line 7), we can see that each one is a tuple with one element for each field we asked for.

Finally, lines 8 and 9 close our cursor and our connection, since the database can only keep a limited number of these open at one time. Since establishing a connection takes time, though, we shouldn’t open a connection, do one operation, then close the connection, only to reopen it a few microseconds later to do another operation. Instead, it’s normal to create one connection that stays open for the lifetime of the program.

# Lab

Read your five different types of your own files to Python from your hard disk.